export const WEATHER_LOADING = "WEATHER_LOADING";
export const WEATHER_ERROR = "WEATHER_ERROR";

export const GET_WEATHER_DONE = "GET_WEATHER_DONE";
export const POST_WEATHER_DONE = "POST_WEATHER_DONE";
// export const PASSWORD_REMOVE_ERROR = "PASSWORD_REMOVE_ERROR";